version: "3.8"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.web
        ports:
            - 8080:80
        networks:
            - app-network
        depends_on:
            - db
    db:
        build:
            context: .
            dockerfile: Dockerfile.db
        networks:
            - app-network
        volumes:
            - "/vagrant/db/images:/var/lib/mysql/images"
        environment:
            MYSQL_ROOT_PASSWORD: "Password1"
networks:
    app-network: